package com.exchange.settlement

import org.slf4j.LoggerFactory
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.stereotype.Service

/**
 * Manages property token issuance and the property_holders projection.
 *
 * createProperty : inserts DB records + creates TB accounts + emits 100% tokens to the
 *                  issuer account (SYSTEM_PROPERTY_OWNER_USER) + seeds property_holders.
 *
 * syncHolder     : reads uid's real balance from TigerBeetle and writes it to
 *                  property_holders. Must be called after any TB transfer that changes
 *                  token ownership for that uid (e.g. after TradeConsumer.settleTrade).
 *
 * TigerBeetle is the source of truth for amounts — property_holders is a projection,
 * reconstructible at any time by scanning all (userId, propertyLedger) accounts in TB.
 *
 * Money-path: proven in PropertyIntegrationTest (emission invariant, conservation,
 * projection fidelity, jurisdiction link). Run: ./gradlew :settlement:propertyTest
 */
@Service
class PropertyService(
    private val settlementService: SettlementService,
    private val jdbc: JdbcTemplate
) {
    private val log = LoggerFactory.getLogger(javaClass)

    /**
     * Emission transfer ID namespace: (1L shl 48) + propertyId.
     * Far above typical trade transferIds (tradeId << 4), collision-free in practice.
     * Deterministic from propertyId → safe to retry after a partial failure.
     */
    private fun emissionTransferId(propertyId: Long): Long = (1L shl 48) + propertyId

    /**
     * Create a property, emit all tokens to the issuer, and seed the holder projection.
     * Returns the new propertyId (auto-generated by Postgres).
     *
     * Idempotency note: if the DB INSERT succeeds but a later step fails, retrying with
     * a different name/ledger will create a new property. To make full creation idempotent,
     * add a unique constraint on property_ledger_id (already present) and catch the conflict.
     */
    fun createProperty(
        name: String,
        jurisdiction: String,
        propertyLedgerId: Int,
        quoteLedgerId: Int,
        symbolId: Int,
        totalTokens: Long
    ): Long {
        val propertyId = jdbc.queryForObject(
            "INSERT INTO properties (name, jurisdiction, property_ledger_id, total_tokens) VALUES (?,?,?,?) RETURNING id",
            Long::class.java, name, jurisdiction, propertyLedgerId, totalTokens
        )!!

        jdbc.update(
            "INSERT INTO symbols (id, property_id, base_ledger_id, quote_ledger_id) VALUES (?,?,?,?)",
            symbolId, propertyId, propertyLedgerId, quoteLedgerId
        )

        // TB: create system accounts (external/fees) and issuer accounts for this ledger
        settlementService.ensureSystemAccounts(propertyLedgerId)
        settlementService.ensureAccount(AccountIds.SYSTEM_PROPERTY_OWNER_USER, propertyLedgerId)

        // Emit 100% of tokens: external(propertyLedger) → available(PROPERTY_OWNER, propertyLedger)
        settlementService.deposit(
            AccountIds.SYSTEM_PROPERTY_OWNER_USER, propertyLedgerId, totalTokens,
            emissionTransferId(propertyId)
        )

        // Seed the projection with the initial state
        syncHolder(propertyId, AccountIds.SYSTEM_PROPERTY_OWNER_USER, propertyLedgerId)

        log.info("Property created: id={} ledger={} jurisdiction={} totalTokens={}",
            propertyId, propertyLedgerId, jurisdiction, totalTokens)
        return propertyId
    }

    /**
     * Read uid's balance from TigerBeetle and write it to property_holders.
     * Upserts: creates the row on first call, updates on subsequent calls.
     */
    fun syncHolder(propertyId: Long, uid: Long, propertyLedgerId: Int) {
        val balance = settlementService.getBalance(uid, propertyLedgerId)
        jdbc.update(
            """INSERT INTO property_holders (property_id, uid, balance_snapshot, updated_at)
               VALUES (?, ?, ?, NOW())
               ON CONFLICT (property_id, uid) DO UPDATE
               SET balance_snapshot = EXCLUDED.balance_snapshot, updated_at = NOW()""",
            propertyId, uid, balance
        )
    }
}
