server:
  port: 8083

spring:
  application:
    name: gateway
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: "true"

logging:
  level:
    com.exchange: DEBUG
